# Generated by Django 6.0.3 on 2026-03-25 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('joining', 'Joining'), ('idle', 'Idle'), ('spectating', 'Spectating'), ('waiting', 'Waiting'), ('playing', 'Playing'), ('left', 'Left'), ('kicked', 'Kicked')], default='joining', max_length=32)),
                ('connection_status', models.CharField(choices=[('connected', 'Connected'), ('disconnected_recoverable', 'Disconnected Recoverable'), ('disconnected_expired', 'Disconnected Expired')], default='connected', max_length=32)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_host', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(default=dict)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participants', to='identities.useridentity')),
            ],
            options={
                'db_table': 'participant',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_code', models.CharField(max_length=32, unique=True)),
                ('invite_token', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('open', 'Open'), ('active', 'Active'), ('idle', 'Idle'), ('closing', 'Closing'), ('closed', 'Closed'), ('expired', 'Expired'), ('archived', 'Archived')], default='created', max_length=32)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public_future', 'Public (Future)')], default='private', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('settings_json', models.JSONField(default=dict)),
                ('created_by_identity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_rooms', to='identities.useridentity')),
                ('host_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_rooms', to='rooms.participant')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rooms.room'),
        ),
        migrations.CreateModel(
            name='RoomTable',
            fields=[
                ('table_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_type', models.CharField(choices=[('lobby', 'Lobby'), ('match', 'Match'), ('tournament', 'Tournament'), ('custom', 'Custom')], max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('idle', 'Idle'), ('closed', 'Closed')], default='open', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('settings_json', models.JSONField(default=dict)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='rooms.room')),
            ],
            options={
                'db_table': 'room_table',
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='current_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_participants', to='rooms.roomtable'),
        ),
    ]
