# Generated by Django 6.0.3 on 2026-03-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_participantroleassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Room Name', max_length=128),
        ),
    ]
