# Generated by Django 6.0.3 on 2026-03-25 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMatch',
            fields=[
                ('game_match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('waiting_for_players', 'Waiting for Players'), ('ready', 'Ready'), ('starting', 'Starting'), ('active', 'Active'), ('paused', 'Paused'), ('interrupted', 'Interrupted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('abandoned', 'Abandoned'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('resumable', models.BooleanField(default=False)),
                ('termination_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('winner_summary_json', models.JSONField(blank=True, null=True)),
                ('config_json', models.JSONField(default=dict)),
                ('snapshot_state_json', models.JSONField(blank=True, null=True)),
                ('metadata_json', models.JSONField(default=dict)),
                ('created_by_participant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_game_matches', to='rooms.participant')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='game_matches', to='games.gamedefinition')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_matches', to='rooms.room')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='game_matches', to='rooms.roomtable')),
            ],
            options={
                'db_table': 'game_match',
            },
        ),
    ]
