# Generated by Django 6.0.3 on 2026-03-26 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMatchAction',
            fields=[
                ('game_match_action_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveBigIntegerField()),
                ('actor_type', models.CharField(choices=[('human', 'Human'), ('bot', 'Bot')], default='human', max_length=16)),
                ('participant_id', models.UUIDField()),
                ('action_type', models.CharField(max_length=64)),
                ('action_payload_json', models.JSONField(default=dict)),
                ('validated', models.BooleanField(default=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('resulting_state_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('game_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='matches.gamematch')),
            ],
            options={
                'db_table': 'game_match_action',
                'constraints': [models.UniqueConstraint(fields=('game_match', 'sequence_number'), name='uq_game_match_action_sequence')],
            },
        ),
    ]
