# Generated by Django 6.0.3 on 2026-03-26 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_gamematchaction'),
        ('rooms', '0002_participant_current_game_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMatchSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_index', models.PositiveIntegerField()),
                ('game_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='matches.gamematch')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_match_seats', to='rooms.participant')),
            ],
            options={
                'ordering': ['seat_index'],
                'constraints': [models.UniqueConstraint(fields=('game_match', 'seat_index'), name='uniq_game_match_seat_index'), models.UniqueConstraint(fields=('game_match', 'participant'), name='uniq_game_match_participant')],
            },
        ),
    ]
