# Generated by Django 6.0.3 on 2026-03-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_matchsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamematch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
