# Generated by Django 6.0.3 on 2026-04-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_gamematch_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamematch',
            name='pending_acceptances',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='gamematch',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('waiting_for_players', 'Waiting for Players'), ('ready', 'Ready'), ('starting', 'Starting'), ('active', 'Active'), ('paused', 'Paused'), ('interrupted', 'Interrupted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('abandoned', 'Abandoned'), ('archived', 'Archived'), ('pending_acceptance', 'Pending Acceptance')], default='draft', max_length=32),
        ),
    ]
