# Generated by Django 6.0.3 on 2026-03-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamedefinition',
            old_name='game_key',
            new_name='game_id',
        ),
    ]
