# Generated by Django 6.0.3 on 2026-03-29 02:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0003_participantroleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('channel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('room', 'Room'), ('table', 'Table'), ('match', 'Match'), ('tournament', 'Tournament')], max_length=32)),
                ('scope_id', models.UUIDField()),
                ('channel_policy_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_channels', to='rooms.room')),
            ],
            options={
                'db_table': 'chat_channel',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('participant', 'Participant'), ('system', 'System')], default='participant', max_length=16)),
                ('sender_id', models.UUIDField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('emoji', 'Emoji'), ('reaction', 'Reaction'), ('system', 'System')], default='text', max_length=16)),
                ('status', models.CharField(choices=[('created', 'Created'), ('delivered', 'Delivered'), ('edited', 'Edited'), ('deleted', 'Deleted')], default='created', max_length=16)),
                ('visibility_policy_json', models.JSONField(default=dict)),
                ('payload_json', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatchannel')),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='chatchannel',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_id'), name='uq_chat_channel_scope'),
        ),
    ]
