# Generated by Django 6.0.3 on 2026-03-25 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('identity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_type', models.CharField(choices=[('guest', 'Guest'), ('registered', 'Registered')], max_length=32)),
                ('display_name', models.CharField(max_length=100)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('guest_session_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('merged', 'Merged')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('metadata_json', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'user_identity',
            },
        ),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('guest_session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token_hash', models.CharField(max_length=255, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('client_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata_json', models.JSONField(default=dict)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_sessions', to='identities.useridentity')),
            ],
            options={
                'db_table': 'guest_session',
            },
        ),
    ]
